alias g="git"
alias cl="clear"
alias tl="tmux ls"
alias ta="tmux attach -t"
alias td="tmux detach-client"
alias tk="tmux kill-session"
alias tlv="tmux select-layout main-vertical"
alias tlh="tmux select-layout main-vertical"
